### ISSUE TITLE
Enable higher core oversubscription for Pods per Core

### ISSUE THREAD

**Issue by williamcaban** [openshift-kni/cnf-features-deploy#525]
For DU profiles consider setting the `podsPerCore: 0` so there is no restrictions on the number of Pods per physical Core (default to 20) and allowing platform workload to have better oversubscription on resource utilization.

Also, since each node by default gets a /23, increasing the node level limit to 500 (default 250) will also help with dense configurations.

```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: max-pods-500 
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: max-pods-500 
  kubeletConfig:
    # unlimited Pods per core
    podsPerCore: 0
    # max Pods per Node (max must be less than node CIDR)
    # For /23, the max IP available are 2^(32-23)-2 = 510
    maxPods: 500 
```

Then apply it to the `master` role for it to be enabled for the SNO

```bash
oc label machineconfigpool master custom-kubelet=max-pods-500
```
